"""Alert-to-control mapper for SOC incident response mode.

Maps Splunk alert keywords to the compliance controls they implicate,
enabling automatic evidence collection when a SIEM alert fires.
"""
from __future__ import annotations

from datetime import datetime, timezone

ALERT_TO_CONTROLS: dict[str, list[str]] = {
    "mfa": ["CC6.1", "A.9.2.3", "PR.AC-1"],
    "login": ["CC6.1", "CC7.2"],
    "privilege": ["CC6.1", "A.9.2.3"],
    "ransomware": ["CC7.2", "RC.RP-1"],
    "data_exfil": ["CC6.1", "A.9.2.3"],
    "anomal": ["CC7.2"],
    "brute": ["CC6.1"],
    "lateral": ["CC6.1", "CC7.2"],
    "phish": ["CC6.1", "CC7.2"],
    "exfiltrat": ["CC6.1", "A.9.2.3"],
    "unauthori": ["CC6.1", "CC7.2"],
}


def map_alert_to_controls(alert_title: str, alert_body: str = "") -> list[str]:
    """Return control IDs most relevant to this alert.

    Scans the combined alert title + body for known keywords and returns
    the union of all matched control IDs. Falls back to CC6.1 (access
    control) if no keywords match.
    """
    text = (alert_title + " " + alert_body).lower()
    matched: set[str] = set()
    for keyword, controls in ALERT_TO_CONTROLS.items():
        if keyword in text:
            matched.update(controls)
    return sorted(matched) or ["CC6.1"]


def build_incident_report(
    alert_payload: dict,
    controls: list[str],
    panel_results: list[dict],
    elapsed: float,
) -> str:
    """Render an incident compliance report as markdown."""
    alert_name = alert_payload.get("alert_name", "Unknown Alert")
    severity = alert_payload.get("severity", "medium")
    triggered = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    result_info = alert_payload.get("result", {})
    count = alert_payload.get("count", result_info.get("count", "N/A"))
    user = alert_payload.get("user", result_info.get("user", "N/A"))

    lines = [
        "# Incident Compliance Report",
        "",
        f"**Alert:** {alert_name}",
        f"**Severity:** {severity}",
        f"**Triggered:** {triggered}",
        f"**Context:** {count} events, user={user}",
        f"**Controls evaluated:** {', '.join(controls)}",
        "",
    ]

    for pr in panel_results:
        control_id = pr["control_id"]
        verdict = pr["verdict"]
        confidence = pr.get("confidence", 0.0)
        rationale = pr.get("rationale", "No rationale provided.")

        lines.append(f"## {control_id}")
        lines.append(f"**Verdict: {verdict}** (confidence: {confidence:.2f})")
        lines.append(f"{rationale}")
        lines.append("")

    lines.append("## Recommended Actions")
    lines.append("")

    action_num = 1
    for pr in panel_results:
        if pr["verdict"] in ("FAIL", "PARTIAL"):
            for rec in pr.get("recommendations", []):
                lines.append(f"{action_num}. {rec}")
                action_num += 1

    if action_num == 1:
        lines.append("No immediate actions required based on current evidence.")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by audit-evidence-compiler incident mode in {elapsed:.1f}s*")

    return "\n".join(lines) + "\n"
