"""aec_demo — hackathon demo entry point.

Usage:
    aec_demo --sample soc2-cc61
    aec_demo --control CC6.1 --window 30d
    aec_demo --sample soc2-cc61 --no-llm
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path

from rich.console import Console
from rich.panel import Panel

console = Console()

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "samples"


def _load_sample(name: str) -> dict:
    """Load a pre-canned snapshot from samples/."""
    path = SAMPLES_DIR / f"{name}.json"
    if not path.exists():
        available = [p.stem for p in SAMPLES_DIR.glob("*.json")]
        console.print(f"[red]Sample '{name}' not found.[/]")
        console.print(f"Available: {', '.join(available)}")
        raise SystemExit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def _load_live(control_id: str, window: str) -> tuple[dict, object]:
    """Fetch live snapshot from Splunk."""
    from aec.splunk.client import SplunkClient
    from aec.splunk.snapshot import fetch_snapshot

    client = SplunkClient()
    return fetch_snapshot(control_id, time_window=window, client=client), client


def _control_text_for(control_id: str) -> str:
    """Return a human-readable description for common controls."""
    texts = {
        "CC6.1": (
            "CC6.1: Logical and physical access controls — the entity implements "
            "logical access security software, infrastructure, and architectures "
            "over protected information assets to protect them from security events."
        ),
        "CC7.2": (
            "CC7.2: The entity monitors system components and the operation of those "
            "components for anomalies that are indicative of malicious acts, natural "
            "disasters, and errors affecting the entity's ability to meet its objectives; "
            "anomalies are analyzed to determine whether they represent security events."
        ),
        "A.9.2.1": (
            "A.9.2.1: User registration and de-registration — a formal user registration "
            "and de-registration process shall be implemented to enable assignment of access rights."
        ),
    }
    return texts.get(control_id, f"Control {control_id}")


def _write_audit_memo(
    snapshot: dict,
    panel_result,
    out_dir: Path,
    ts: str,
    elapsed: float,
) -> Path:
    """Generate a human-readable audit memo from the panel result."""
    lines = [
        f"# Audit Memo — {snapshot['control_id']} ({snapshot['framework']})",
        f"Generated: {ts}",
        f"Evidence source: {snapshot.get('snapshot_name', 'live')}",
        f"Time range: {snapshot['time_range']['earliest']} to {snapshot['time_range']['latest']}",
        f"Events analyzed: {snapshot['event_count']}",
        "",
        "## Verdict",
        "",
        f"**{panel_result.final_verdict}** (consensus: {panel_result.consensus_method})",
        "",
        "## Panel Summary",
        "",
    ]

    for c in panel_result.critiques:
        lines.append(f"### {c.persona.capitalize()} ({c.model})")
        lines.append(f"- Verdict: {c.verdict} (confidence: {c.confidence:.0%})")
        lines.append(f"- Rationale: {c.rationale}")
        if c.concerns:
            lines.append("- Concerns:")
            for concern in c.concerns:
                lines.append(f"  - {concern}")
        lines.append("")

    lines.append("## Key Evidence")
    lines.append("")
    agg = snapshot.get("aggregations", {})
    if agg:
        for k, v in agg.items():
            if isinstance(v, float):
                lines.append(f"- {k}: {v:.0%}")
            else:
                lines.append(f"- {k}: {v}")
    lines.append("")

    lines.append("## SPL Query")
    lines.append("")
    lines.append(f"```spl\n{snapshot.get('search', 'N/A')}\n```")
    lines.append("")

    adversary = next((c for c in panel_result.critiques if c.persona == "adversary"), None)
    if adversary and adversary.recommended_additional_searches:
        lines.append("## Recommended Follow-up Searches")
        lines.append("")
        for spl in adversary.recommended_additional_searches:
            lines.append(f"- `{spl}`")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by audit-evidence-compiler in {elapsed:.1f}s*")

    memo_path = out_dir / f"audit_memo_{ts}.md"
    memo_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return memo_path


async def _run(args: argparse.Namespace) -> None:
    start = time.monotonic()
    splunk_client = None

    # Step 1: Load snapshot
    if args.sample:
        snapshot = _load_sample(args.sample)
        console.print(
            f"[bold cyan][1/4][/] Loading snapshot: samples/{args.sample}.json "
            f"({snapshot['event_count']} events, "
            f"{snapshot['time_range']['earliest']} to {snapshot['time_range']['latest']})"
        )
    else:
        console.print(f"[bold cyan][1/4][/] Fetching live snapshot for {args.control}...")
        snapshot, splunk_client = _load_live(args.control, args.window)
        console.print(
            f"      Fetched {snapshot['event_count']} events "
            f"({snapshot['time_range']['earliest']} to {snapshot['time_range']['latest']})"
        )

    control_id = snapshot["control_id"]
    control_text = _control_text_for(control_id)

    if args.no_llm:
        console.print("[yellow][2/4] Skipping panel (--no-llm)[/]")
        console.print(Panel(json.dumps(snapshot, indent=2), title="Snapshot", border_style="cyan"))
        return

    # Step 2: Run panel
    console.print("[bold cyan][2/4][/] Running panel debate (3 personas, parallel)...")

    from aec.agent.panel import run_panel
    from aec.agent.panel_view import PanelView

    view = PanelView(console=console)
    view.start()

    try:
        panel_result = await run_panel(
            snapshot=snapshot,
            control_text=control_text,
            spl_executed=snapshot.get("search", ""),
            splunk_snapshot=snapshot,
            splunk_client=splunk_client,
            time_window=args.window,
            view=view,
        )
    finally:
        view.stop()

    # Step 3: Consensus
    verdict_style = (
        "green" if panel_result.final_verdict == "PASS"
        else "yellow" if panel_result.final_verdict == "PARTIAL"
        else "red"
    )

    adversary = next((c for c in panel_result.critiques if c.persona == "adversary"), None)
    consensus_detail = ""
    if adversary and adversary.concerns:
        consensus_detail = f" — adversary surfaced: {adversary.concerns[0]}"

    console.print(
        f"[bold cyan][3/4][/] Consensus: "
        f"[bold {verdict_style}]{panel_result.final_verdict}[/]"
        f"{consensus_detail}"
    )

    if panel_result.adversary_followups:
        console.print("      Included adversary follow-up search results in transcript")

    # Step 4: Write artifacts
    out_dir = Path("out")
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")

    from aec.agent.panel import _format_transcript_file

    snapshot_name = snapshot.get("snapshot_name", "unknown")
    transcript_content = _format_transcript_file(panel_result, control_id, snapshot_name)

    transcript_path = out_dir / f"transcript_{ts}.md"
    transcript_path.write_text(transcript_content, encoding="utf-8")

    elapsed = time.monotonic() - start
    memo_path = _write_audit_memo(snapshot, panel_result, out_dir, ts, elapsed)

    console.print(f"[bold cyan][4/4][/] Wrote {transcript_path}")
    console.print(f"      Wrote {memo_path}")

    total = time.monotonic() - start
    console.print(f"[bold green]Done in {total:.0f}s.[/]")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit Evidence Compiler — Splunk hackathon demo"
    )
    parser.add_argument(
        "--control",
        help="Control ID (e.g., CC6.1, A.9.2.1, PR.AC-1)",
    )
    parser.add_argument(
        "--window",
        default="30d",
        help="Time window for Splunk search (default: 30d)",
    )
    parser.add_argument(
        "--sample",
        help="Use pre-canned snapshot (e.g., soc2-cc61). Bypasses live Splunk.",
    )
    parser.add_argument(
        "--no-llm",
        action="store_true",
        help="Skip panel debate — just show snapshot (debugging)",
    )

    args = parser.parse_args()

    # Allow AEC_SAMPLE env var as shortcut
    if not args.sample and os.environ.get("AEC_SAMPLE"):
        args.sample = os.environ["AEC_SAMPLE"]

    if not args.sample and not args.control:
        parser.error("Provide --sample or --control")

    asyncio.run(_run(args))


if __name__ == "__main__":
    main()
