#!/usr/bin/env python3
"""Generate splunk-app/auditcompiler/default/savedsearches.conf from catalog.json.

Each control gets a scheduled saved search that:
  1. Runs the evidence SPL from the catalog's spl_skeleton hint
  2. Pipes the rows through | auditcompiler control=<id> mode=summary
  3. Collects the result into index=auditcompiler_posture

Searches are staggered 5 minutes apart within each 4-hour window to avoid
thundering herd against the panel APIs.

Usage:
    python scripts/generate_savedsearches.py
    python scripts/generate_savedsearches.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "src" / "aec" / "priors" / "catalog.json"
OUTPUT_PATH = REPO_ROOT / "splunk-app" / "auditcompiler" / "default" / "savedsearches.conf"

# BOTS v3 dataset window (2018) — match what aec_demo uses
BOTS_EARLIEST = "2018-08-01"
BOTS_LATEST = "2018-09-30"

# Generic fallback SPL when the catalog hint doesn't have a usable skeleton
FALLBACK_SPL = (
    "index=botsv3 earliest={earliest} latest={latest} "
    "| head 200"
)

HEADER = """\
# ============================================================
# Audit Evidence Compiler — Scheduled Saved Searches
# AUTO-GENERATED by scripts/generate_savedsearches.py
# Do not edit by hand — re-run the generator instead.
#
# Each search:
#   1. Runs the evidence SPL from catalog.json
#   2. Pipes through | auditcompiler control=<id> mode=summary
#   3. Collects into index=auditcompiler_posture
#
# Schedule: every 4 hours, staggered 5 min per control.
# ============================================================

"""


def primary_framework(ctrl: dict) -> str:
    """Return the most important framework label for a control."""
    fw = ctrl.get("frameworks", {})
    for name in ("SOC 2", "ISO 27001", "NIST 800-53", "NIST CSF", "COBIT"):
        if fw.get(name):
            return name
    return "SOC 2"


def clean_spl_skeleton(skeleton: str) -> str:
    """Make the skeleton safe to drop into a savedsearches stanza value.

    - Strip leading/trailing whitespace
    - Collapse internal newlines to spaces (Splunk conf values are single-line)
    - Ensure it targets botsv3 index if no index is already specified
    """
    s = " ".join(skeleton.split())

    # If the skeleton doesn't start with | (generating command) and doesn't
    # reference an index, constrain it to botsv3 with the BOTS time window.
    if not s.startswith("|") and "index=" not in s:
        s = f"index=botsv3 earliest={BOTS_EARLIEST} latest={BOTS_LATEST} {s}"
    elif "earliest=" not in s and not s.startswith("|"):
        # Has an index but no time bound — add the BOTS window
        s = s.replace("index=", f"earliest={BOTS_EARLIEST} latest={BOTS_LATEST} index=", 1)

    return s


def build_stanza(ctrl: dict, index: int) -> str:
    """Return the savedsearches.conf stanza for one control."""
    ctrl_id = ctrl["internal_id"]        # e.g. CTRL-001
    ctrl_name = ctrl["name"]             # e.g. Patch Management
    fw = primary_framework(ctrl)

    # Stagger: 5 minutes apart per control, cycling through 0..59 minutes
    minute_offset = (index * 5) % 60
    cron = f"{minute_offset} */4 * * *"

    # Build evidence SPL
    hint = ctrl.get("splunk_hint", {})
    skeleton = hint.get("spl_skeleton", "")
    if skeleton:
        evidence_spl = clean_spl_skeleton(skeleton)
    else:
        evidence_spl = FALLBACK_SPL.format(earliest=BOTS_EARLIEST, latest=BOTS_LATEST)

    # Collect command adds metadata fields so the dashboard query can group by them
    collect_cmd = (
        f'eval control_id="{ctrl_id}", '
        f'ctrl_name="{ctrl_name}", '
        f'framework="{fw}"'
        f" | collect index=auditcompiler_posture"
    )

    full_search = (
        f"{evidence_spl} "
        f"| auditcompiler control={ctrl_id} mode=summary "
        f"| {collect_cmd}"
    )

    return (
        f"[AEC - {ctrl_id} {ctrl_name}]\n"
        f"search = {full_search}\n"
        f"cron_schedule = {cron}\n"
        f"enableSched = 1\n"
        f"dispatch.earliest_time = {BOTS_EARLIEST}\n"
        f"dispatch.latest_time = {BOTS_LATEST}\n"
        f"alert.track = 0\n"
        f"description = AEC auto-generated: evidence for {ctrl_id} ({fw})\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing to disk",
    )
    args = parser.parse_args()

    catalog = json.loads(CATALOG_PATH.read_text())
    controls = catalog.get("controls", [])
    if not controls:
        print("ERROR: No controls found in catalog.json", file=sys.stderr)
        sys.exit(1)

    stanzas = [build_stanza(ctrl, i) for i, ctrl in enumerate(controls)]
    output = HEADER + "\n".join(stanzas)

    if args.dry_run:
        print(output)
    else:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(output)
        print(f"Written {len(stanzas)} stanzas to {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
